# Generated by Django 2.1.7 on 2019-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(help_text='This is help text.', max_length=255, unique=True, verbose_name='My Field:')),
            ],
        ),
    ]
